### ISSUE TITLE
Sequoia no longer on CRAN

### ISSUE THREAD

**Issue by BEFH** [JiscaH/sequoia#13]
The package has been removed as seen here: [link](https://cran.r-project.org/package=sequoia)

The page says this:

> Package ‘sequoia’ was removed from the CRAN repository.
>
> Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/sequoia).
>
> Archived on 2021-12-06 as check problems were not corrected in time.

**Comment by JiscaH** [comment]
Hi, I know, I didn't manage to fix things in the time I had available then. I'm currently working on trying to reproduce the issues they reported, and hopefully in a few weeks it'll be on CRAN again.
