### ISSUE TITLE
Known crosses as prior info

### ISSUE THREAD

**Issue by ronahuel** [JiscaH/sequoia#14]
Dear, thank you for releasing this package which has been very helpful for my analysis.
I have searched for information on this and have not been able to find out if it is possible to tell sequoia in any way cross pairs as a priori information. I have pairs of males and females that we know were crossed, but we need to assign which offspring were generated by those crosses. In doing so without prior, and unfortunately due to a low amount of high quality SNPs we receive (app 50), the generated assignment does not correspond correctly to the crosses we know a priori, i.e. offspring are assigned to mothers and fathers that we know were not outcrossed.

Is there a way to incorporate this information into the analysis? Thank you in advance for your help.

**Comment by JiscaH** [comment]
Hi, no this is not currently possible in sequoia, but it's an interesting case. In most cases the results for parentage assignment are very clear-cut whether or not two individuals are parent and offspring, and it's very rare that giving the crosses as a priori information / conditioning on them would help. And the chance of label swaps or breeders jumping over fences etc. is never zero...
