### ISSUE TITLE
  installation of package ‘/var/folders/dc/5j3hs53s2cn0lhr1ps49slfw0000gn/T//RtmpNYHr2z/file1c0916e8a227/sequoia_2.3.3.tar.gz’ had non-zero exit status

### ISSUE THREAD

**Issue by jzehnpfennig** [JiscaH/sequoia#17]
Hi, 
I am trying to get sequoia for R, and I am running into some errors. Any help would be appreciated. 
Thank you! 

Downloading GitHub repo JiscaH/sequoia@stable
✔  checking DESCRIPTION meta-information ... /5j3hs53s2cn0lhr1ps49slfw0000gn/T/RtmpNYHr2z/remotes1c093ea83438/JiscaH-sequoia-85ea741/DESCRIPTION’ ...
─  cleaning src
   Warning: file 'sequoia/cleanup' did not have execute permissions: corrected
   Warning: file 'sequoia/cleanup' did not have execute permissions: corrected
* installing *source* package ‘sequoia’ ...
** using staged installation
** libs
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  Sequoia.f90 -o Sequoia.o
make: gfortran: No such file or directory
make: *** [Sequoia.o] Error 1
ERROR: compilation failed for package ‘sequoia’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/sequoia’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/dc/5j3hs53s2cn0lhr1ps49slfw0000gn/T//RtmpNYHr2z/file1c0916e8a227/sequoia_2.3.3.tar.gz’ had non-zero exit status

**Comment by JiscaH** [comment]
Hi! 

If I understand the error message correctly, the problem is that it can't find gfortran, which it needs to compile the R package. I think if you install gfortran first, then it should work.

I'm not a Mac person so I'm afraid I can't help you in more detail!
