### ISSUE TITLE
Silly question for a very usefull package

### ISSUE THREAD

**Issue by jblamyatifremer** [JiscaH/sequoia#2]
Hi Jisca, 

I am sure that you have a R trick to access to dam object stored in compareOUT$Counts...
        
## get assignation statistic for dam
compareOUT <- PedCompare(Ped1=ped1,Ped2=SeqOUT$Pedigree)
dam <- compareOUT$Counts[1] ## NOT WORKING
dam <- unlist(compareOUT$Counts)[1] ## NOT WORKING

best regards, 

JB

**Comment by JiscaH** [comment]
Hello,

There are no stupid questions! (only not-sufficiently-clear help files...)

compareOUT$Counts is what R calls an 'array', and you get the dam part as
dam <- compareOUT$Counts[, , "dam"] # or
dam <- compareOUT$Counts[, , 1]

Glad you find the package useful! Out of personal curiosity - what 
species are you working on?

cheers,
Jisca

**Comment by jblamyatifremer** [comment]
Perfect ! 
I am working on oysters (successive hermaphrodite) populations or bi-parental cross. Most of the time, we do have an observed pedigree, and we are now accumulating HTS data. I am measuring the amount of putative errors in the observed pedigree. 
I am also planning to  use your package to design lower snp panel density for assignations, imputations from public array.   
I close this thread. 
Thanks you again for your time.
