### ISSUE TITLE
ErrM not found with DuplicateCheck

### ISSUE THREAD

**Issue by sinnweja** [JiscaH/sequoia#9]
From the example in the vignette, the call to sequoia with MaxSubIter=1, you get an error that it can't find ErrM in the DuplicateCheck function.  However, ErrM is an element of ParOUT, so you should make sure to pass ParOUT$ErrM to DuplicateCheck.  Here is code that gets the error and shows a work-around.

`
library(sequoia")
data(Ped_HSg5, LH_HSg5)
set.seed(1000)
Geno <- SimGeno(Ped = Ped_HSg5, nSnp = 200)
Geno[1:5,1:5]
ParOUT <- sequoia(GenoM = Geno, LifeHistData = LH_HSg5, MaxSibIter = 0)
names(ParOUT)
table(is.na(ParOUT$PedigreePar[,2]))
SeqOUT <- sequoia(GenoM = Geno, SeqList = ParOUT, MaxSibIter = 1)
## gets error
SeqOUT <- sequoia(GenoM = Geno, SeqList = ParOUT, MaxSibIter = 1, Err=1e-4)
## gets error, but this allows ErrM to be found so it can run
ErrM <- ParOUT$ErrM
SeqOUT <- sequoia(GenoM = Geno, SeqList = ParOUT, MaxSibIter = 1)
`

**Comment by JiscaH** [comment]
Please see my reply to your other post.
